
if GetLocale() ~= "ruRU" then return end
local _, sm = ...
local L = sm.L
L["1. Background"] = "Фон"
L["2. Border"] = "Граница"
L["3. Artwork"] = "Тема"
L["4. Overlay"] = "Наложение" -- Needs review
L["5. Highlight"] = "Подсветка"
L["Add Blend (additive)"] = "Добавить Размытие (дополнительное)" -- Needs review
L["Addon Buttons"] = "Кнопки Аддонов"
L["A global profile already exists. You will be switched over to it and your UI will be reloaded, are you sure?"] = "Общий профиль уже существует. Вы уверены, что хотите включить его? Это вызовет перезагрузку интерфейса." -- Needs review
L["Allow SexyMap to assume drag ownership for buttons attached to the minimap. Turn this off if you have another mod that you want to use to position your minimap buttons."] = "Разрешить SexyMap двигать кнопки, присоединенные к мини-карте. Выключите это, если у вас есть другой мод, который вы хотите использовать для изменения позиций кнопок миникарты" -- Needs review
L["Alpha Key (1-bit alpha)"] = "Основная прозрачность (1-бит)" -- Needs review
L["Always"] = "Всегда" -- Needs review
L["Are you sure you want to switch back to using a character specific profile? This will reload your UI."] = "Вы уверены, что хотите снова использовать уникальный для персонажа профиль? Это вызовет перезагрузку интерфейса." -- Needs review
L["Armored Man"] = "Требуется детальный перевод в контексте." -- Needs review
L["A static amount to rotate the texture by."] = "Значение для поворота текстуры " -- Needs review
L["Auto Zoom-Out Delay"] = "Задержка авто-отдаления" -- Needs review
L["Backdrop Color"] = "Цвет заднего фона" -- Needs review
L["Backdrop Insets"] = "Вставки на заднем плане" -- Needs review
L["Background Color"] = "Цвет фона"
L["Background/edge"] = "Фон/край"
L["Background Texture"] = "Текстура фона"
L["Blend Mode"] = "Режим размытия"
L["Blend (normal)"] = "Размытие (норма)"
L["Border Color"] = "Цвет границы"
L["Border Edge Size"] = "Размер края границы"
L["Borders"] = "Границы"
L["Border Texture"] = "Текстура границы"
L["Boss Frames"] = "Фреймы боссов"
L["Buttons"] = "Кнопки" -- Needs review
L["Calendar"] = "календарь" -- Needs review
L["Capture Bars"] = "Бар захвата" -- Needs review
L["Challenge Mode Button (When Available)"] = "Кнопка режима испытаний (если доступна)" -- Needs review
L["Circle"] = "Круг" -- Needs review
L["Clamp to screen"] = "Прикрепить к экрану" -- Needs review
L["Clear & start over"] = "Очистить и начать сначала" -- Needs review
L["Clear the current borders and start fresh"] = "Очистить текущие границы и начать заново" -- Needs review
L["Clock"] = "Часы" -- Needs review
L["Coordinates"] = "Координаты" -- Needs review
L["Copy a Profile"] = "Скопировать профиль" -- Needs review
L["Copying this profile will reload your UI, are you sure?"] = "Вы уверены, что хотите скопировать этот профиль? Это вызовет перезагрузку интерфейса." -- Needs review
L["Create a new border"] = "Создать новую границу" -- Needs review
L["Current Borders"] = "Текущие границы" -- Needs review
L["Default Presets"] = "Стандартные предустановки"
L["Delete"] = "Удалить" -- Needs review
L["Delete a Profile"] = "Удалить профиль" -- Needs review
L["Diamond"] = "Бриллиант" -- Needs review
L["Disable (opaque)"] = "Отключить (непрозрачность)" -- Needs review
L["Disable Rotation"] = "Отключить поворот" -- Needs review
L["Disabling the movers will make them reset next time you relog, are you sure?"] = "Вы уверены, что хотите отключить передвижение фреймов? Их положение сбросится при следующем входе в игру." -- Needs review
L["Drag Radius"] = "Радиус перетягивания" -- Needs review
L["Dungeon Difficulty Indicator (When Available)"] = "Индикатор сложности подземелий (если доступен)" -- Needs review
L["Dynamic Buttons"] = "Динамические кнопки" -- Needs review
L["Enable"] = "Включить" -- Needs review
L["Enable a backdrop and border for the minimap. This will let you set square borders more easily."] = "Включить фон и границу миникарты. Это упростит установку квадратных границ." -- Needs review
L["Enable a HUD minimap. This is very useful for gathering resources, but for technical reasons, the HUD map and the normal minimap can't be shown at the same time. Showing the HUD map will turn off the normal minimap."] = "Включить HUD-миникарту. Это очень удобно для добывания ресурсов, но, по техническим причинам, HUD-миникарта и обычная миникарта не могут отображаться одновременно. Включение HUD-миникарты выключит обычную миникарту." -- Needs review
L["Enable Coordinates"] = "Включить координаты" -- Needs review
L["Enable Hudmap"] = "Включить HUD-карту" -- Needs review
L["Enable Minimap Fader"] = "Включить затухание миникарты" -- Needs review
L["Enable Movers"] = "Включить ползунки" -- Needs review
L["Enter a name to create a new border. The name can be anything you like to help you identify that border."] = "Введите имя для новой границы. В качестве имени можно ввести что угодно, что поможет вам распознать эту границу." -- Needs review
L["Enter the full path to a texture to use. It's recommended that you use something like |cffff6600TexBrowser|r to find textures to use."] = "Введите полный путь к текстуре, которую хотите использовать. Для поиска текстур желательно используйте отдельную программу, например |cffff6600TexBrowser|r." -- Needs review
L["Entry Options"] = "Настройки элемента" -- Needs review
L["Faded Circle (Large)"] = "Исчезающий круг (большой)" -- Needs review
L["Faded Circle (Small)"] = "Исчезающий круг (мелкий)" -- Needs review
L["Faded Square"] = "Исчезающий квадрат" -- Needs review
L["Fader"] = "Уровень видимости" -- Needs review
L["Font"] = "Шрифт" -- Needs review
L["Font Color"] = "Цвет шрифта" -- Needs review
L["Font Size"] = "Размер шрифта" -- Needs review
L["Force a square texture. Fixed distortion on square textures."] = "Делать текстуру квадратной. Постоянное искажение на квадратных текстурах." -- Needs review
L["Garrison Button (When Available)"] = "кнопку гарнизона (если доступен)" -- Needs review
L["Guild Dungeon Difficulty Indicator (When Available)"] = "индикатор сложности подземелья в составе группы гильдии (если доступно)" -- Needs review
L["Heart"] = "Сердце" -- Needs review
L["Height"] = "Высота"
L["Hexagon"] = "Шестиугольник" -- Needs review
L["Hide default border"] = "Скрывать стандартные границы" -- Needs review
L["Hide the default border on the minimap."] = "Скрывать стандартную границу на миникарте." -- Needs review
L["Horizontal Nudge"] = "Сдвиг по горизонтали" -- Needs review
L["Horizontal Position"] = "Расположение по горизонтали" -- Needs review
L["Hover Opacity"] = "Прозрачность при наведении" -- Needs review
L["HUD Color"] = "Цвет HUD" -- Needs review
L["If you zoom into the map, this feature will automatically zoom out after the selected period of time (seconds). Using a value of 0 will disable Auto Zoom-Out."] = "Включив эту опцию, после приближения миникарты через некоторое время (в секундах) произойдет автоматическое отдаление. Есть выставить значение 0, то автоматическое отдаление миникарты происходить не будет." -- Needs review
L["Keybinding"] = "Назначение клавиш" -- Needs review
L["Layer"] = "Слой" -- Needs review
L["Let SexyMap control button visibility"] = "Разрешить SexyMap регулировать видимость кнопок" -- Needs review
L["Let SexyMap handle button dragging"] = "Разрешить SexyMap перетаскивать кнопки" -- Needs review
L["Lock Button Dragging"] = "Запретить перетаскивание кнопок" -- Needs review
L["Lock Minimap"] = "Закрепить миникарту" -- Needs review
L["Lock Movers"] = "Закрепить передвижение фреймов." -- Needs review
L["Map Button"] = "кнопку карты" -- Needs review
L["Minimap shape"] = "Форма миникарты" -- Needs review
L["Mod Blend (modulative)"] = "Изменить размытие (регулируемо)" -- Needs review
L["Movers"] = "Передвижение фреймов." -- Needs review
L["Movers Warning"] = "ВНИМАНИЕ: Эта функция официально не поддерживается. При ее использовании могут возникнуть такие проблемы, как лишние текстуры, нефункционирование отслеживания заданий или появляющиеся не в тех местах фреймы босса. Фреймы Blizzard, такие как отслеживание заданий и здоровье босса не предназначены для передвижения. Желательно, используйте аддоны для замены этих фреймов, например, Unit Frames для здоровья босса." -- Needs review
L["Name"] = "Имя" -- Needs review
L["Never"] = "Никогда"
L["New Mail Indicator (When Available)"] = "индикатор непрочитанной почты (когда она есть)" -- Needs review
L["No global profile exists. Your current profile will be copied over and used as the global profile, are you sure? This will also reload your UI."] = "Не найден общий профиль. Вы уверены, что хотите создать общий профиль, используя настройки текущего профиля? Это вызовет перезагрузку интерфейса." -- Needs review
L["Normal Opacity"] = "Обычная прозрачность" -- Needs review
L["Objectives Tracker"] = "Отслеживание целей" -- Needs review
L["Octagon"] = "Восьмиугольник" -- Needs review
L["On Hover"] = "При наведении" -- Needs review
L["Opacity"] = "Прозрачность" -- Needs review
L["Open TexBrowser"] = "Открыть TexBrowser" -- Needs review
L["Ping"] = "Сигнал" -- Needs review
L["Preset"] = "Предустановка"
L["Prevent the minimap from being moved off the screen"] = "Запретить перемещение миникарты за пределы экрана" -- Needs review
L["Profiles"] = "Профили" -- Needs review
L["Queue Status (PvP/LFG) Button (When Available)"] = "кнопку очереди (ПвП/ЛФГ, если доступно)" -- Needs review
L["Quickly change the look of your minimap by using a minimap preset."] = "Вы можете быстро поменять вид миникарты выбрав одну из предустановок" -- Needs review
L["Really delete this border?"] = "Вы уверены, что хотите удалить эту границу?" -- Needs review
L["Really delete this preset? This can't be undone."] = "Вы уверены, что хотите удалить эту предустановку? Изменения будут необратимы." -- Needs review
L["Really delete this profile?"] = "Вы уверены, что хотите удалить этот профиль?" -- Needs review
L["(Requires button visibility control in the Buttons menu)"] = "(Регулирование видимости кнопок должно быть включено в меню Кнопки)" -- Needs review
L["Reset Current Profile"] = "Сбросить настройки текущего профиля" -- Needs review
L["Resetting this profile will reload your UI, are you sure?"] = "Вы уверены, что хотите сбросить настройки этого профиля?. Это вызовет перезагрузку интерфейса." -- Needs review
L["Right Click Configure"] = "Настройки по правой кнопке мыши"
L["Right clicking the map will open the SexyMap options"] = "Нажатие правой кнопки мыши по карте откроет настройки SexyMap"
L["Rotation Speed (seconds)"] = "Скорость вращения (в секундах)"
L["Rounded - Bottom Left"] = "Закругленный - слева внизу" -- Needs review
L["Rounded - Bottom Right"] = "Закругленный - справа внизу" -- Needs review
L["Rounded - Top Left"] = "Закругленный - слева вверху" -- Needs review
L["Rounded - Top Right"] = "Закругленный - справа вверху" -- Needs review
L["Route 66"] = "Route 66" -- Needs review
L["Save current settings as preset..."] = "Сохранить текущие настройки как предустановку..." -- Needs review
L["Scale"] = "Масштаб" -- Needs review
L["Select a preset to load settings from. This will erase any of your current borders."] = "Выберите предустановку для загрузки настроек. Ваши текущие настройки границ будут сброшены." -- Needs review
L["Select preset to load"] = "Выберите предустановку для загрузки настроек" -- Needs review
L["SharedMedia Border"] = "Граница SharedMedia" -- Needs review
L["SharedMedia Texture"] = "Текстура SharedMedia" -- Needs review
L["Show inside chat"] = "Показывать в чате" -- Needs review
L["Show North Tag"] = "Показывать сторону севера" -- Needs review
L["Show on minimap"] = "Показывать на миникарте" -- Needs review
L["Show %s:"] = "Показывать %s:" -- Needs review
L["Show who pinged"] = "Показывать кто сигналит" -- Needs review
L["Snowflake"] = "Снежинка" -- Needs review
L["Spice up your minimap with some sexy options."] = "Придайте вашей миникарте потрясающий вид." -- Needs review
L["Square"] = "Квадрат" -- Needs review
L["Standard Buttons"] = "Стандартные кнопки" -- Needs review
L["Static Rotation"] = "Вращение на постоянную величину" -- Needs review
L["TexBrowser Not Installed"] = "TexBrowser не установлено" -- Needs review
L["Text Color"] = "Цвет текста" -- Needs review
L["Texture"] = "Текстура" -- Needs review
L["Texture Options"] = "Настройки текстуры" -- Needs review
L["Texture Path"] = "Путь к текстуре" -- Needs review
L["Texture Tint"] = "Оттенок текстуры" -- Needs review
L["Text Width"] = "Ширина текста" -- Needs review
L["The HudMap supports several addons. If you have any of the addons below installed, they will be shown on the HudMap."] = "HUD-карта поддерживает некоторые модификации. Если у вас установлены любые модификации, перечисленные ниже, то они отобразятся на HUD-карте." -- Needs review
L["The time it takes (in seconds) to complete one rotation. A setting of 0 turns off rotation."] = "Время, которое занимает один полный оборот (в секундах). Есть выставить значение 0, то текстура вращаться не будет." -- Needs review
L["This will wipe out any current settings!"] = "Все текущие настройки будут сброшены!" -- Needs review
L["Tile Background"] = "Фон плитки" -- Needs review
L["Tile Size"] = "Размер плитки" -- Needs review
L["Toggle HudMap On/Off"] = "Включить/выключить HudMap" -- Needs review
L["Tracking Button"] = "кнопку отслеживания" -- Needs review
L["Turn this off if you want another mod to handle which buttons are visible on the minimap."] = "Выключите если хотите, чтобы другой аддон контролировал видимость кнопок на миникарте." -- Needs review
L["Use Global Profile"] = "Включить общий профиль"
L["User-Submitted Presets"] = "Пользовательские предустановки"
L["Use the global profile if you want the same look on every character, or use a character-specific profile for a unique look on each character."] = "Включите общий профиль если вы хотите, чтобы у всех персонажей миникарта выглядела одинаково, или выберите отдельный профиль для каждого персонажа." -- Needs review
L["Vehicle Seat"] = "Место в транспорте" -- Needs review
L["Vertical Nudge"] = "Сдвиг по вертикали" -- Needs review
L["Vertical Position"] = "Расположение по вертикали" -- Needs review
L["Visibility"] = "Видимость" -- Needs review
L["Width"] = "Ширина"
L["You can set a background and edge file for the minimap like you would with any frame. This is useful when you want to create static square backdrops for your minimap."] = "Вы можете установить для миникарты фон и файл границы так же, как и для любого другого фрейма." -- Needs review
L["Zone Text"] = "Текст игровой зоны" -- Needs review
L["Zoom In Button"] = "кнопку приближения" -- Needs review
L["Zoom Out Button"] = "кнопку отдаления" -- Needs review

--L.updateRate = "Update Rate (seconds)"
--L.updateRateDesc = "The lower the value, the faster the coordinates will update, but the more memory and CPU will be consumed due to asking the game for fresh coordinate data."
